source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

def shared_pods
pod 'Kingfisher', '~> 4.6.1'
pod 'Toaster', '~> 2.0'
pod 'UITextView+Placeholder', '~> 1.2'
pod 'Whisper'
pod 'GSImageViewerController'
pod 'ReachabilitySwift'
pod 'Alamofire'
pod 'AMPopTip', '~> 3.1.1'
pod 'SWXMLHash', '~> 4.0.0'
pod 'IQKeyboardManagerSwift'
pod 'YPImagePicker' , '~> 2.3.0'
end

target 'Kantor Tanpa Jeda' do
shared_pods
end
